<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Concerns\OwnsRecords; use App\Models\Expense; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Validation\Rule;
class ExpenseController extends Controller { use OwnsRecords;
 public function index(Request $r){$q=$r->user()->expenses()->with(['category','paymentMethod']);if($r->filled('from'))$q->whereDate('date','>=',$r->from);if($r->filled('to'))$q->whereDate('date','<=',$r->to);if($r->filled('category'))$q->where('category_id',$r->category);if($r->filled('search'))$q->where(fn($x)=>$x->where('description','like','%'.$r->search.'%')->orWhere('notes','like','%'.$r->search.'%'));$items=$q->latest('date')->latest('id')->paginate(15)->withQueryString();$categories=$r->user()->categories()->orderBy('name')->get();return view('expenses.index',compact('items','categories'));}
 public function create(Request $r){return view('expenses.create',['categories'=>$r->user()->categories()->orderBy('name')->get(),'methods'=>$r->user()->paymentMethods()->orderBy('name')->get()]);}
 public function store(Request $r){$d=$this->validated($r);$d['user_id']=$r->user()->id;if($r->hasFile('receipt'))$d['receipt']=$r->file('receipt')->store('receipts','public');$e=Expense::create($d);ActivityLogController::record($r,'created','expense',$e->id,'Recorded expense of '.$d['amount']);if($r->wantsJson())return response()->json(['success'=>true,'id'=>$e->id,'message'=>'Expense recorded.']);if($r->input('action')==='save_and_new')return to_route('expenses.create')->with('success','Expense recorded. Add another below.');return to_route('expenses.index')->with('success','Expense recorded.');}
 public function show(Request $r,Expense $expense){$this->authorizeOwner($r,$expense);return view('expenses.show',compact('expense'));}
 public function edit(Request $r,Expense $expense){$this->authorizeOwner($r,$expense);return view('expenses.edit',compact('expense')+['categories'=>$r->user()->categories()->orderBy('name')->get(),'methods'=>$r->user()->paymentMethods()->orderBy('name')->get()]);}
 public function update(Request $r,Expense $expense){$this->authorizeOwner($r,$expense);$d=$this->validated($r);if($r->hasFile('receipt')){if($expense->receipt)Storage::disk('public')->delete($expense->receipt);$d['receipt']=$r->file('receipt')->store('receipts','public');}$expense->update($d);return to_route('expenses.index')->with('success','Expense updated.');}
 public function destroy(Request $r,Expense $expense){$this->authorizeOwner($r,$expense);if($expense->receipt)Storage::disk('public')->delete($expense->receipt);$expense->delete();return back()->with('success','Expense deleted.');}
 private function validated(Request $r):array{return $r->validate(['category_id'=>['nullable',Rule::exists('categories','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'payment_method_id'=>['nullable',Rule::exists('payment_methods','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'amount'=>'required|numeric|min:0.01|max:9999999999','description'=>'nullable|string|max:255','date'=>'required|date|before_or_equal:today','notes'=>'nullable|string|max:2000','receipt'=>'nullable|file|mimes:jpg,jpeg,png,pdf|max:5120']);}
}
