<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Concerns\OwnsRecords; use App\Models\Income; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class IncomeController extends Controller { use OwnsRecords;
 public function index(Request $r){$q=$r->user()->incomes()->with(['incomeSource','paymentMethod']);if($r->filled('from'))$q->whereDate('date','>=',$r->from);if($r->filled('to'))$q->whereDate('date','<=',$r->to);if($r->filled('source'))$q->where('income_source_id',$r->source);if($r->filled('search'))$q->where(fn($x)=>$x->where('description','like','%'.$r->search.'%')->orWhere('notes','like','%'.$r->search.'%'));$items=$q->latest('date')->latest('id')->paginate(15)->withQueryString();$sources=$r->user()->incomeSources()->orderBy('name')->get();return view('incomes.index',compact('items','sources'));}
 public function create(Request $r){return view('incomes.create',['sources'=>$r->user()->incomeSources()->orderBy('name')->get(),'methods'=>$r->user()->paymentMethods()->orderBy('name')->get()]);}
 public function store(Request $r){$d=$this->validated($r);$d['user_id']=$r->user()->id;$i=Income::create($d);ActivityLogController::record($r,'created','income',null,'Recorded income of '.$d['amount']);if($r->wantsJson())return response()->json(['success'=>true,'id'=>$i->id,'message'=>'Income recorded.']);if($r->input('action')==='save_and_new')return to_route('incomes.create')->with('success','Income recorded. Add another below.');return to_route('incomes.index')->with('success','Income recorded.');}
 public function show(Request $r,Income $income){$this->authorizeOwner($r,$income);return view('incomes.show',compact('income'));}
 public function edit(Request $r,Income $income){$this->authorizeOwner($r,$income);return view('incomes.edit',compact('income')+['sources'=>$r->user()->incomeSources()->orderBy('name')->get(),'methods'=>$r->user()->paymentMethods()->orderBy('name')->get()]);}
 public function update(Request $r,Income $income){$this->authorizeOwner($r,$income);$income->update($this->validated($r));return to_route('incomes.index')->with('success','Income updated.');}
 public function destroy(Request $r,Income $income){$this->authorizeOwner($r,$income);$income->delete();return back()->with('success','Income deleted.');}
 private function validated(Request $r):array{return $r->validate(['income_source_id'=>['nullable',Rule::exists('income_sources','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'payment_method_id'=>['nullable',Rule::exists('payment_methods','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'amount'=>'required|numeric|min:0.01|max:9999999999','description'=>'nullable|string|max:255','date'=>'required|date|before_or_equal:today','notes'=>'nullable|string|max:2000']);}
}
