<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Concerns\OwnsRecords; use App\Models\RecurringTransaction; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class RecurringTransactionController extends Controller { use OwnsRecords;
 public function index(Request $r){$items=$r->user()->recurringTransactions()->with(['category','incomeSource','paymentMethod'])->latest('next_due_date')->paginate(15);return view('recurring.index',compact('items'));}
 public function create(Request $r){return view('recurring.create',['item'=>new RecurringTransaction(['type'=>'expense','frequency'=>'monthly','start_date'=>today(),'next_due_date'=>today(),'is_active'=>true]),'categories'=>$r->user()->categories()->orderBy('name')->get(),'sources'=>$r->user()->incomeSources()->orderBy('name')->get(),'methods'=>$r->user()->paymentMethods()->orderBy('name')->get()]);}
 public function store(Request $r){$d=$this->validated($r);$d['user_id']=$r->user()->id;RecurringTransaction::create($d);return to_route('recurring-transactions.index')->with('success','Recurring transaction created.');}
 public function show(Request $r,RecurringTransaction $recurring_transaction){$this->authorizeOwner($r,$recurring_transaction);return view('recurring.show',['item'=>$recurring_transaction]);}
 public function edit(Request $r,RecurringTransaction $recurring_transaction){$this->authorizeOwner($r,$recurring_transaction);return view('recurring.edit',['item'=>$recurring_transaction,'categories'=>$r->user()->categories()->orderBy('name')->get(),'sources'=>$r->user()->incomeSources()->orderBy('name')->get(),'methods'=>$r->user()->paymentMethods()->orderBy('name')->get()]);}
 public function update(Request $r,RecurringTransaction $recurring_transaction){$this->authorizeOwner($r,$recurring_transaction);$recurring_transaction->update($this->validated($r));return to_route('recurring-transactions.index')->with('success','Recurring transaction updated.');}
 public function destroy(Request $r,RecurringTransaction $recurring_transaction){$this->authorizeOwner($r,$recurring_transaction);$recurring_transaction->delete();return back()->with('success','Recurring transaction deleted.');}
 private function validated(Request $r):array{return $r->validate(['type'=>'required|in:income,expense','amount'=>'required|numeric|min:0.01','description'=>'nullable|string|max:255','category_id'=>['nullable',Rule::exists('categories','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'income_source_id'=>['nullable',Rule::exists('income_sources','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'payment_method_id'=>['nullable',Rule::exists('payment_methods','id')->where(fn($q)=>$q->where('user_id',$r->user()->id))],'frequency'=>'required|in:daily,weekly,monthly,yearly','start_date'=>'required|date','next_due_date'=>'required|date','end_date'=>'nullable|date|after_or_equal:start_date','is_active'=>'nullable|boolean']);}
}
